context:
  title: This is my title
  text: Click down here
  images:
    - src: https://store-images.s-microsoft.com/image/apps.21425.13510798886710834.33fdad4e-90bc-4c13-8672-ffae78ea758d.174eebad-9fcd-4b76-9f83-3124dd9ec247?w=96&h=96&q=60
      text: Click me
    - src: https://store-images.s-microsoft.com/image/apps.21425.13510798886710834.33fdad4e-90bc-4c13-8672-ffae78ea758d.174eebad-9fcd-4b76-9f83-3124dd9ec247?w=96&h=96&q=60
      text: Click me
    - src: http://cdn.images.express.co.uk/img/dynamic/galleries/64x64/76618.jpg
      text: Click me
